package main

import "fmt" //autogenerated import package

func main() { // function to be run on compiler
	// fmt stands for "format" I/O
	// function for printing
	fmt.Print("hello world")
	fmt.Println("loh kok nyambunng") // print with auto enter
	fmt.Print("oh dah pisah")        // ordinary print
	fmt.Print("\n")                  // enter to next line
	fmt.Println("nama \t alamat")    // wider space as tab
}
